.PHONY: clean All

All:
	@echo "----------Building project:[ xx - Debug ]----------"
	@cd "xx" && "$(MAKE)" -f  "xx.mk"
clean:
	@echo "----------Cleaning project:[ xx - Debug ]----------"
	@cd "xx" && "$(MAKE)" -f  "xx.mk" clean
