.PHONY: clean All

All:
	@echo "----------Building project:[ flipflip_irq_ack - Debug ]----------"
	@cd "flipflip_irq_ack" && "$(MAKE)" -f  "flipflip_irq_ack.mk" && "$(MAKE)" -f  "flipflip_irq_ack.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ flipflip_irq_ack - Debug ]----------"
	@cd "flipflip_irq_ack" && "$(MAKE)" -f  "flipflip_irq_ack.mk" clean
