.PHONY: clean All

All:
	@echo "----------Building project:[ ascii_display - Debug ]----------"
	@cd "ascii_display" && "$(MAKE)" -f  "ascii_display.mk" && "$(MAKE)" -f  "ascii_display.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ ascii_display - Debug ]----------"
	@cd "ascii_display" && "$(MAKE)" -f  "ascii_display.mk" clean
